version: '3.8'

services:
  llamacpp:
    image: joshxt/local-llm:cpu
    env_file: .env
    restart: unless-stopped
    ports:
      - "8091:8091"
      - "8080:8080"
    volumes:
      - ./models:/app/models