version: '3.8'

services:
  local-llm:
    image: ghcr.io/josh-xt/local-llm:cpu-dev
    environment:
      - LOCAL_LLM_API_KEY=${LOCAL_LLM_API_KEY-}
      - DEFAULT_MODEL=${DEFAULT_MODEL-phi-2-dpo}
      - VOICE_ENABLED=${VOICE_ENABLED-true}
    restart: unless-stopped
    ports:
      - "8091:8091"
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
      - ./voices:/app/voices