version: '3.8'

services:
  local-llm:
    image: ghcr.io/josh-xt/local-llm:cuda-dev-add-stt
    environment:
      - LOCAL_LLM_API_KEY=${LOCAL_LLM_API_KEY-}
      - GPU_LAYERS=10
      - MAIN_GPU=0
      - DEFAULT_MODEL=${DEFAULT_MODEL-phi-2-dpo}
    ports:
      - "8091:8091"
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
      - ./voices:/app/voices
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
