version: '3.8'

services:
  local-llm:
    image: joshxt/local-llm:vulkan
    environment:
      - LOCAL_LLM_URL=${LOCAL_LLM_URL-http://localhost:8091}
      - LOCAL_LLM_API_KEY=${LOCAL_LLM_API_KEY-}
      - GPU_LAYERS=${GPU_LAYERS-0}
      - MAIN_GPU=${MAIN_GPU-0}
      - DEFAULT_MODEL=${DEFAULT_MODEL-phi-2-dpo}
      - WHISPER_MODEL=${WHISPER_MODEL-base.en}
      - CUDA_DOCKER_ARCH=all
    restart: unless-stopped
    ports:
      - "8091:8091"
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
      - ./voices:/app/voices
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
