name: Publish Docker image

on:
  push:
    branches: [add-stt, dev]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - llamacpp_image: "python:3-slim-bullseye"
            platforms: "linux/amd64,linux/arm64/v8"
            tag_name: "cpu-dev"
          - llamacpp_image: "nvidia/cuda:12.1.1-devel-ubuntu22.04"
            platforms: "linux/amd64"
            tag_name: "cuda-dev"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platforms }}
          push: true
          tags: |
            ghcr.io/josh-xt/local-llm:${{ matrix.tag_name }}
            ghcr.io/josh-xt/local-llm:${{ matrix.tag_name }}-${{ github.sha }}
          build-args: |
            LLAMACPP_IMAGE=${{ matrix.llamacpp_image }}

  test-local-llm:
    uses: josh-xt/AGiXT/.github/workflows/operation-test-with-jupyter.yml@main
    with:
      notebook: tests/tests.ipynb
      image: ghcr.io/josh-xt/local-llm:cpu-dev
      port: "8091"
      additional-python-dependencies: openai requests
    needs: build_and_push
