name: Publish Development Docker images

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: "Dockerfile"
            platforms: "linux/amd64"
            tag_name: "cpu-dev"
          - dockerfile: "cuda.Dockerfile"
            platforms: "linux/amd64"
            tag_name: "cuda-dev"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Branch Name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/[^a-zA-Z0-9._-]/-/g')" >> $GITHUB_ENV
        id: extract_branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lowercase GitHub User and Repo Name
        run: |
          echo "GITHUB_USER=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f 2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: |
            ghcr.io/${{ env.GITHUB_USER }}/${{ env.REPO_NAME }}:${{ matrix.tag_name }}-${{ env.BRANCH_NAME }}
            ghcr.io/${{ env.GITHUB_USER }}/${{ env.REPO_NAME }}:${{ matrix.tag_name }}-${{ env.BRANCH_NAME }}-${{ github.sha }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ matrix.tag_name }}-${{ env.BRANCH_NAME }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ matrix.tag_name }}-${{ env.BRANCH_NAME }}-${{ github.sha }}

  test-local-llm:
    uses: josh-xt/AGiXT/.github/workflows/operation-test-with-jupyter.yml@main
    with:
      notebook: tests/tests.ipynb
      image: ghcr.io/josh-xt/local-llm:cpu-dev
      port: "8091"
      additional-python-dependencies: openai requests
    needs: build_and_push
